version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name:  web-Todoapp
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
#       - DJANGO_SETTINGS_MODULE=core.settings
        - DEBUG=True
        - SECRET_KEY=secret_key