version: '3.9'

services:

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    container_name:  web-Todoapp
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Changed from static to staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
#       - DJANGO_SETTINGS_MODULE=core.settings
        - DEBUG=False
        - SECRET_KEY=secret_key
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery-worker
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  beat:
    build: .
    container_name: celery-beat
    command: celery -A core beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - web
      - redis


volumes:
  static_volume:
  media_volume: